apiVersion: v1
kind: Pod
metadata:
  name: environement
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        value: devops
      - name: trainer
        value: chaithanya